### ISSUE TITLE
Unable get payment options

### ISSUE THREAD

**Issue by Loisgenesis** [techquest/isw_mobile_sdk_flutter#1]
HI, I have been trying to use this package without any luck, I was unable to access the payment option page, after initialising payment by clicking a custom button I created, The popup screen loads for a moment and displays an error that says `unable get payment options`.

**Reproduction steps**
I followed the steps in the README.MD file and only added merchant credentials and client parameters.

**Image**
<img width="387" alt="Screenshot 2020-03-03 at 4 30 08 PM" src="https://user-images.githubusercontent.com/39795779/75791034-46914c80-5d6c-11ea-9fcb-66c16748192c.png">

**Comment by ebi-igweze** [comment]
Hello, this could happen because of a couple of reasons, 
1. You're providing invalid credentials, that could be solved by providing the right which could be gotten from your business account at business.quickteller.com,
2. You're pointing to the TEST environment It might just be network issues,  you could try it again.

let me know if either solves the issue for you.

**Comment by Loisgenesis** [comment]
Thanks, I will give it a try and let you know if it works

**Comment by Loisgenesis** [comment]
Hi ebi. I tried setting up a business account with different credentials but I kept getting a 409 error each time I launch the developer tools option from the dashboard. Any advise on how to proceed since its an important step in obtaining the credentials necessary to use this package

**Comment by jogapps** [comment]
I get the unable get payment options. I have  used valid merchant details, still no progress. What's is wrong with the package?

**Comment by ebi-igweze** [comment]
hello @Loisgenesis have you been able to create merchant credentials now

**Comment by ebi-igweze** [comment]
@jogapps 
1. are you trying transactions on test or production environment?
2. are there any errors in the logs that indicate any network issues?

**Comment by jogapps** [comment]
I've tried both. Test and production. And even SANDBOX, its still showing me the same thing

**Comment by jogapps** [comment]
And I'm using the interswitch sandbox details: 

Clientid: IKIACA67D931869E40BE07EE418A0B07A4A6D9EEF588
Secret: y0FISAGAS+OSIASec5Cts/khsWVXaWCoxZcLF2d8o/A=

Merchantcode: MX1209

**Comment by jogapps** [comment]
If the sandbox details are incorrect, please help me with the right details

**Comment by ebi-igweze** [comment]
@jogapps plese can you delete your last messages for the 

> And I'm using the interswitch sandbox details:
> 
> 
> Merchantcode: MX1209

@jogapps please delete the message with your credentails thank you.

**Comment by ebi-igweze** [comment]
> And I'm using the interswitch sandbox details:

>

**Comment by ebi-igweze** [comment]
> And I'm using the interswitch sandbox details:

> -----

@jogapps please delete this message

**Comment by ebi-igweze** [comment]
@jogapps I will get back to you on this in a moment

**Comment by ebi-igweze** [comment]
Hello @jogapps the package currently only supports two modes: TEST and PRODUCTION. Both values can be gotten from either test mode or live mode on the merchant portal https://business.quickteller.com/

**Comment by jogapps** [comment]
Thank you very  much for the support. But its still not working

**Comment by jogapps** [comment]
Its finally working, thank you @ebi-igweze.
I commented the first initialization, since it can only be initialized once. 


// -- remove this one
// initialize the sdk
// await IswMobileSdk.initialize(config);

// --- Leave this one
// intialize with environment, default is Environment.TEST
await IswMobileSdk.initialize(config, Environment.PRODUCTION);
